### ISSUE TITLE
Data Migration from Private to Public IPFS Gateways via Filebase

### ISSUE THREAD

**Issue by jaybuidl** [kleros/builder-baseline#23]
**Notes by @Harman-singh-waraich:** https://hackmd.io/@-cmxt73kRVi2uFMhhabm4A/subgraph-migration

Blocks #22 because the Graph indexers cannot retrieve data from private IPFS gateways anymore.

- [x] Make a small test to ensure that existing files uploaded via Filebase can be accessed with the same IPFS URI (regardless of which gateway is used)
- [x] Upload all existing IPFS content to Filebase

**Comment by salgozino** [comment]
All the files were migrated to the `kleros` bucket in filebase.
There is a cronjob that will keep syncing the kleros ipfs nodes with filebase until we migrate the usage of gateways in the different dapps.

![Image](https://github.com/kleros/builder-baseline/assets/9450450/0df2770c-238e-4158-87c3-33b690a2c365)

Due to the ipfs-cluster dynamic some file could be missed in filebase, but those cases should be handled one by one
